# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "COSTAS 2017"
email: "costas2017@etkinlikler.uzem.omu.edu.tr"
description: "COSTAS 2017"
baseurl: "/costas2017"
url: "http://etkinlikler.uzem.omu.edu.tr"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "OMÜ UZEM"
organizerAlternateName: "OMÜ Distance Education Center"
organizerDescription: "It conducts research and development and application studies related to distance education."
organizerEmail: "costas2017@etkinlikler.uzem.omu.edu.tr"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://uzem.omu.edu.tr/"

# Head
metaKeywords: "costas, uzem"
twitterAccount: ""
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Committees"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/important_dates/", text: "Important Dates"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "COSTAS 2017"
eventDate: "September 13-15, 2017"
typeoutTextValues: '"13", "14", "15"'
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About COSTAS 2017"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The International Conference on COSTAS, organized by the Ondokuz Mayıs University - Faculty of Science will take place from 12th September to the 14st September 2017 in Samsun, Turkey. COSTAS 2017 is intended to bring academicians and researchers to share new advances and improvements in all fields of computational and applied sciences.  The conference will cover several scientific areas such as statistics, computer science, engineering business and econometrics etc. Our sincere thanks go to Distance Education Center (UZEM) in Ondokuz Mayıs University, for supporting and motivating us in every respect. Our congress provides online participation facility with video conference system for researchers who cannot join to the conference. The online presentations can be done with the assistance of technical possibility of UZEM. We invite all academic and non-academic researchers to contribute our conference." }

# Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Ondokuz Mayıs University Distance Education Center, Kurupelit Campus"
eventAddressLocality: "Samsun"
eventAddressLocalityRegion: "Atakum"
eventPostalCode: "55200"
eventAddressCountry: "Turkey"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "41.3691922, 36.1980414"
mapCenterCoordinates: "41.3691922, 36.1980414"
mapMobileCenterCoordinates: "41.3691922, 36.1980414"

# Important Dates
importantDates:
  - {description: "Dead Line For Abstract Submission", date: ""}
  - {description: "Registration Deadline", date: ""}
  - {description: "Late Registration Deadline", date: ""}
  - {description: "Conference Date", date: ""}
importantDatesBigImage: "calendar.jpg" 

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueTitle: "UZEM CONFERENCE HALLS"
venueFeatures: ["Large and small conference halls", "Quality audio system", "Located directly in the university"]

# Partners Block
organizersTitle: "Organizers"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: ""
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Registration fee includes the coffee-tea-cookies, lunches, gala dinner, and online book of abstracts, a conference bag and the certificate of participation/presentation. Reduced conference fees are available for students via the online registration system. When checking in at the conference, students will be asked to provide a copy of a valid Student ID, a confirmation from the supervisor, or other formal evidence of the student status. Due to limited capacity, early registration is recommended. One author can submit three virtual presentation in the congress by one registration fee. Author must pay an extra fee (€20 or 50 TL) if they wish to present more than three virtual presentation."
ticketsOffers:
 -
  name: "Academic (Early)"
  priceForeign: "100"
  priceForeignCurrency: "EUR"
  priceDomestic: "300"
  priceDomesticCurrency: "TRY"
  ticketsNumber: "150"
  buyButtonLink: "#"
  buyButtonText: "Buy Now"
  validFrom: "2017-04-27T10:00"
  validThrough: "2017-05-31T23:59"
  disabled: false
 -
  name: "Academic"
  priceForeign: "150"
  priceForeignCurrency: "EUR"
  priceDomestic: "350"
  priceDomesticCurrency: "TRY"
  ticketsNumber: "150"
  buyButtonLink: "#"
  buyButtonText: "Buy Now"
  validFrom: "2017-06-01T10:00"
  validThrough: "2017-06-30T23:59"
  disabled: true
 -
  name: "Student (Early)"
  priceForeign: "80"
  priceForeignCurrency: "EUR"
  priceDomestic: "200"
  priceDomesticCurrency: "TRY"
  ticketsNumber: "150"
  buyButtonLink: "#"
  buyButtonText: "Buy Now"
  validFrom: "2017-04-27T10:00"
  validThrough: "2017-05-31T23:59"
  disabled: false
 -
  name: "Student"
  priceForeign: "100"
  priceForeignCurrency: "EUR"
  priceDomestic: "250"
  priceDomesticCurrency: "TRY"
  ticketsNumber: "150"
  buyButtonLink: "#"
  buyButtonText: "Buy Now"
  validFrom: "2017-06-01T10:00"
  validThrough: "2017-06-30T23:59"
  disabled: true
 -
  name: "Virtual Presentation"
  priceForeign: "80"
  priceForeignCurrency: "EUR"
  priceDomestic: "150"
  priceDomesticCurrency: "TRY"
  ticketsNumber: "150"
  buyButtonLink: "#"
  buyButtonText: "Buy Now"
  validFrom: "2017-04-27T10:00"
  validThrough: "2017-06-30T23:59"
  disabled: false

# Footer
socialLinks:
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://uzem.omu.edu.tr/", text: "UZEM.omu.edu.tr"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:costas2017@etkinlikler.uzem.omu.edu.tr ", text: "costas2017@etkinlikler.uzem.omu.edu.tr "}

# Speakers List Block
showSessions: true

# Team Block

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "41.3691922, 36.1980414"
logisticsMapMobileCenterCoordinates: "41.3691922, 36.1980414"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
